# Generated by Django 4.2.4 on 2023-08-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='game_name',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
