# Generated by Django 4.2.3 on 2023-08-22 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main_page", "0003_alter_team_members_member"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Team_members",
            new_name="Members",
        ),
    ]
