# Generated by Django 4.2.4 on 2023-08-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_team_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='college',
            field=models.CharField(default='faltu sa koi', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
