# Generated by Django 4.2.4 on 2023-08-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamPlayer', '0001_initial'),
        ('Team', '0003_alter_team_college_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(to='TeamPlayer.teamplayer'),
        ),
    ]
