# Generated by Django 4.2.3 on 2023-08-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='player_first_name',
            new_name='player_name',
        ),
        migrations.RemoveField(
            model_name='players',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='player_last_name',
        ),
    ]
