# Generated by Django 4.2.4 on 2023-08-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_team_college'),
        ('Game', '0002_alter_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(to='Team.team'),
        ),
    ]
