# Generated by Django 4.2.4 on 2023-08-21 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institute_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team',
            new_name='game',
        ),
        migrations.DeleteModel(
            name='Team_members',
        ),
        migrations.AddField(
            model_name='team_member',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.team'),
        ),
    ]
