# Generated by Django 4.2.4 on 2023-08-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_team_member_rename_team_team_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
