# Generated by Django 4.2.4 on 2023-08-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_team_age_team_institute_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
    ]
