# Generated by Django 4.2.4 on 2023-08-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='team_name',
            field=models.CharField(default='null', max_length=60),
        ),
    ]
